---
- name: Mettre a jour le cache apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Mettre a jour tous les paquets
  apt:
    upgrade: dist

- name: Installer les paquets de base
  apt:
    name:
      - curl
      - vim
      - git
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
