[front_group]
front ansible_host=51.44.222.105

[back_group]
back ansible_host=10.0.2.11

[db_group]
db ansible_host=10.0.2.104

[back_group:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/todoapp-key -W %h:%p ubuntu@51.44.222.105"'

[db_group:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/todoapp-key -W %h:%p ubuntu@51.44.222.105"'

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/todoapp-key
ansible_python_interpreter=/usr/bin/python3
